### ISSUE TITLE
모달에 데이터를 전달하고 싶습니다.

### ISSUE THREAD

**Issue by lym7733** [ax5ui/ax5ui-modal#5]
안녕하세요.
고생 많으십니다.

모달창에 object를 전달하고 싶을때는 어떻게 해야 하나요~?

modal.open({
        width: 600,
        iframe: {
            method: "get",
            url: "../modal/PopNotice_html.jsp",
            param: "dataObj="+dataObj
        },
        onStateChanged: function () {
            // mask
            if (this.state === "open") {
                mask.open();
            }
            else if (this.state === "close") {
                mask.close();
            }
        }
    }

위와같이 param으로 전달은 하였는데 
받는곳에서 어떻게 받아줘야 할지 모르겠습니다.

**Comment by thomasJang** [comment]
받는쪽에선 jsp에서 파라미터로 받으시면 되어요. 
https://www.google.com/search?q=jsp+request.getparameter&oq=jsp+request&aqs=chrome.1.69i57j0l5.5862j0j7&sourceid=chrome&ie=UTF-8 여기에서 처럼요.

스크립트로만 하시려면 https://developer.mozilla.org/ko/docs/Web/API/Location 여기를 참고하세요.

**Comment by lym7733** [comment]
감사합니다^^
